import { supabase } from '../lib/supabase';
export interface ClubBrand { id: string; name: string; short_name: string; logo_url: string | null; primary_color: string; secondary_color: string; official_team_page_url?: string | null; official_team_id?: number | null; official_season_id?: number | null; official_source_checked_at?: string | null; official_source_status?: 'unverified' | 'available' | 'blocked' | 'invalid' | null }
export const defaultBrand: ClubBrand = { id: 'default', name: 'מועדון חדש', short_name: 'מועדון', logo_url: null, primary_color: '#0A2341', secondary_color: '#FFFFFF', official_source_status: 'unverified' };
export const clubService = {
  async getBrand(): Promise<ClubBrand> { if (!supabase) return defaultBrand; const { data, error } = await supabase.from('clubs').select('id,name,short_name,logo_url,primary_color,secondary_color,official_team_page_url,official_team_id,official_season_id,official_source_checked_at,official_source_status').limit(1).maybeSingle(); if (error || !data) return defaultBrand; return data as ClubBrand; },
  async updateBrand(id: string, input: Pick<ClubBrand, 'name' | 'short_name' | 'logo_url' | 'primary_color' | 'secondary_color' | 'official_team_page_url' | 'official_team_id' | 'official_season_id' | 'official_source_checked_at' | 'official_source_status'>) { if (!supabase) throw new Error('Supabase is not configured'); const { data, error } = await supabase.from('clubs').update(input).eq('id', id).select('id').maybeSingle(); if (error) throw error; if (!data) throw new Error('לא נמצא מועדון לעדכון. הריצו את שאילתת האיפוס פעם נוספת או צרו רשומת מועדון ב־Supabase.'); },
  async uploadLogo(clubId: string, file: File) { if (!supabase) throw new Error('Supabase is not configured'); const extension = file.name.split('.').pop()?.toLowerCase() || 'png'; const path = `${clubId}/logo-${Date.now()}.${extension}`; const { error } = await supabase.storage.from('club-logos').upload(path, file, { upsert: false, contentType: file.type }); if (error) throw error; return supabase.storage.from('club-logos').getPublicUrl(path).data.publicUrl; },
  parseOfficialTeamUrl(value: string) { try { const url = new URL(value); if (url.hostname !== 'www.football.org.il' || url.pathname !== '/team-details/') return null; const teamId = Number(url.searchParams.get('team_id')); const seasonId = Number(url.searchParams.get('season_id')); return Number.isInteger(teamId) && Number.isInteger(seasonId) ? { url: `https://www.football.org.il/team-details/?season_id=${seasonId}&team_id=${teamId}`, teamId, seasonId } : null; } catch { return null; } },
  async checkOfficialSource(url: string) { if (!supabase) throw new Error('Supabase is not configured'); const { data: { session } } = await supabase.auth.getSession(); if (!session) throw new Error('Unauthorized'); const response = await fetch('/.netlify/functions/ifa-team-source', { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ url }) }); const text = await response.text(); let data: { status?: 'available' | 'blocked'; teamId?: number; seasonId?: number; error?: string }; try { data = JSON.parse(text) as typeof data; } catch { throw new Error('בדיקת מקור זמינה לאחר פריסה ל־Netlify או בהרצה מקומית דרך netlify dev. הקישור עצמו עדיין נשמר בהגדרות.'); } if (!response.ok && data.status !== 'blocked') throw new Error(data.error || 'Source check failed'); return data; }
};
