import { supabase } from '../lib/supabase';
import type { PlayerTotals } from '../types/domain';
export interface PlayerPerformance { playerSeasonId: string; fullName: string; squadStatus: string; expectedAbsenceUntil: string | null; appearances: number; starts: number; substituteAppearances: number; substituted: number; unusedSubstitutes: number; minutes: number; goals: number; assists: number; yellowCards: number; redCards: number }
type StatsRow = { minutes_played: number; goals: number; assists: number; yellow_cards: number; red_cards: number; started: boolean; entered_minute: number | null; exited_minute: number | null; squad_status: 'not_in_squad' | 'unused_substitute' | 'starter' | 'substitute' };
type SeasonRow = { id: string; squad_status: string; expected_absence_until: string | null; players: { full_name: string } | null; match_player_stats: StatsRow[] | null };
export const statisticsService = {
  async playerTotals(): Promise<PlayerTotals[]> { if (!supabase) return []; const { data, error } = await supabase.from('player_statistics').select('*').order('minutes', { ascending: false }); if (error) throw error; return data as PlayerTotals[]; },
  async playerPerformance(): Promise<PlayerPerformance[]> { if (!supabase) return []; const { data, error } = await supabase.from('player_seasons').select('id,squad_status,expected_absence_until,players(full_name),match_player_stats(minutes_played,goals,assists,yellow_cards,red_cards,started,entered_minute,exited_minute,squad_status)').order('id'); if (error) throw error; return (data as unknown as SeasonRow[]).map((season) => { const stats = season.match_player_stats ?? []; const appearances = stats.filter((item) => item.started || item.minutes_played > 0).length; return { playerSeasonId: season.id, fullName: season.players?.full_name ?? 'שחקן ללא שם', squadStatus: season.squad_status, expectedAbsenceUntil: season.expected_absence_until, appearances, starts: stats.filter((item) => item.started).length, substituteAppearances: stats.filter((item) => item.squad_status === 'substitute' && item.minutes_played > 0).length, substituted: stats.filter((item) => item.exited_minute !== null).length, unusedSubstitutes: stats.filter((item) => item.squad_status === 'unused_substitute').length, minutes: stats.reduce((sum, item) => sum + item.minutes_played, 0), goals: stats.reduce((sum, item) => sum + item.goals, 0), assists: stats.reduce((sum, item) => sum + item.assists, 0), yellowCards: stats.reduce((sum, item) => sum + item.yellow_cards, 0), redCards: stats.reduce((sum, item) => sum + item.red_cards, 0) }; }).sort((a, b) => a.fullName.localeCompare(b.fullName, 'he')); }
};
