import { useState } from 'react';
import { ImageUp, Save } from 'lucide-react';
import { PageHeader, PrimaryButton } from '../components/ui';
import { useBrand } from '../contexts/BrandContext';
import { clubService } from '../services/clubService';

export function ClubSettingsPage() {
  const { brand, refresh } = useBrand(); const [name, setName] = useState(brand.name); const [shortName, setShortName] = useState(brand.short_name); const [primary, setPrimary] = useState(brand.primary_color); const [secondary, setSecondary] = useState(brand.secondary_color); const [logo, setLogo] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); setBusy(true); try { const logoUrl = logo ? await clubService.uploadLogo(brand.id, logo) : brand.logo_url; await clubService.updateBrand(brand.id, { name, short_name: shortName, logo_url: logoUrl, primary_color: primary, secondary_color: secondary }); await refresh(); setMessage('המיתוג נשמר והוחל באפליקציה.'); } catch { setMessage('לא ניתן לשמור את המיתוג. ודאו שהרצתם את migration 007 ושיש לכם הרשאת אדמין.'); } finally { setBusy(false); } };
  return <><PageHeader title="מיתוג הקבוצה" description="שם, לוגו וצבעים המוחלים על מסך הכניסה ועל כל הממשק."/><form className="page-form brand-settings" onSubmit={submit}><fieldset><legend>זהות המועדון</legend><label className="form-field">שם הקבוצה<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label className="form-field">שם קצר<input value={shortName} onChange={(event) => setShortName(event.target.value)} required /></label></fieldset><fieldset><legend>לוגו</legend><div className="brand-logo-preview" style={{ backgroundColor: secondary }}><img src={logo ? URL.createObjectURL(logo) : brand.logo_url || '/maccabi-kfar-saba-logo-transparent.png'} alt="תצוגה מקדימה של לוגו" /></div><label className="button secondary upload-control"><ImageUp size={17}/>בחרו קובץ לוגו<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => setLogo(event.target.files?.[0] ?? null)} /></label><small>PNG, JPG או WebP עד 5MB. מומלץ לוגו על רקע שקוף.</small></fieldset><fieldset><legend>צבעי ממשק</legend><div className="form-grid"><label className="form-field">צבע ראשי<input type="color" value={primary} onChange={(event) => setPrimary(event.target.value)} /></label><label className="form-field">צבע משני<input type="color" value={secondary} onChange={(event) => setSecondary(event.target.value)} /></label></div></fieldset>{message && <p className={message.startsWith('לא ניתן') ? 'form-error' : 'success-message'}>{message}</p>}<div className="form-actions"><PrimaryButton type="submit" disabled={busy}><Save size={17}/>{busy ? 'שומר…' : 'שמירת מיתוג'}</PrimaryButton></div></form></>;
}
