import type { FormEventHandler, ReactNode } from 'react';
import { zodResolver } from '@hookform/resolvers/zod';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { useNavigate, useParams } from 'react-router-dom';
import { LoadingSkeleton, PageHeader, PrimaryButton, SecondaryButton } from '../components/ui';
import { playersService } from '../services/playersService';
import { matchesService } from '../services/matchesService';
import type { Match, Player } from '../types/domain';

const playerSchema = z.object({ full_name: z.string().trim().min(2, 'יש להזין שם מלא.'), shirt_number: z.string().refine((value) => value === '' || (/^\d+$/.test(value) && Number(value) >= 1 && Number(value) <= 99), 'מספר חולצה חייב להיות בין 1 ל־99.'), primary_position: z.string().min(1, 'יש לבחור תפקיד ראשי.'), secondary_position: z.string().optional(), squad_status: z.enum(['active','injured','overload','suspended','inactive']), expected_absence_until: z.string().optional(), birth_date: z.string().optional(), dominant_foot: z.enum(['right','left','both']).optional(), previous_club: z.string().optional(), professional_notes: z.string().optional() }).refine((value) => !value.expected_absence_until || ['injured','overload'].includes(value.squad_status), { path: ['expected_absence_until'], message: 'צפי היעדרות רלוונטי רק לפציעה או עומס יתר.' });
const matchSchema = z.object({ opponent_name: z.string().trim().min(2, 'יש להזין שם יריבה.'), competition_name: z.string().trim().min(2, 'יש להזין מסגרת.'), match_date: z.string().optional(), kickoff_time: z.string().optional(), home_or_away: z.enum(['home','away']), venue: z.string().optional() });
type PlayerValues = z.infer<typeof playerSchema>; type MatchValues = z.infer<typeof matchSchema>;

export function PlayerFormPage() {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id); const [player, setPlayer] = useState<Player | null | undefined>(editing ? undefined : null); const [error, setError] = useState('');
  const { register, handleSubmit, watch, reset, formState: { errors, isSubmitting } } = useForm<PlayerValues>({ resolver: zodResolver(playerSchema), defaultValues: { squad_status: 'active', shirt_number: '' } });
  useEffect(() => { if (!id) return; void playersService.list().then((items) => { const current = items.find((item) => item.id === id) ?? null; setPlayer(current); if (current) { const season = current.player_seasons[0]; reset({ full_name: current.full_name, shirt_number: season?.shirt_number?.toString() ?? '', primary_position: season?.primary_position ?? '', secondary_position: season?.secondary_position ?? '', squad_status: season?.squad_status ?? 'active', expected_absence_until: season?.expected_absence_until ?? '', birth_date: current.birth_date ?? '', dominant_foot: undefined, previous_club: '', professional_notes: '' }); } }).catch(() => setPlayer(null)); }, [id, reset]);
  const status = watch('squad_status'); const unavailable = status === 'injured' || status === 'overload';
  const submit = async (values: PlayerValues) => { setError(''); try { const input = { ...values, shirt_number: values.shirt_number ? Number(values.shirt_number) : undefined, expected_absence_until: unavailable ? values.expected_absence_until : undefined }; if (player) await playersService.update(player, input); else await playersService.create(input); navigate(editing ? `/players/${id}` : '/players'); } catch { setError('לא ניתן לשמור את השחקן. השינויים לא נשמרו.'); } };
  if (editing && player === undefined) return <LoadingSkeleton lines={5} />;
  if (editing && !player) return <section className="empty-state"><h2>השחקן לא נמצא</h2></section>;
  return <FormLayout title={editing ? 'עריכת שחקן' : 'הוספת שחקן'} description="הפרטים הבסיסיים והמקצועיים לעונה הנוכחית" onCancel={() => navigate(editing ? `/players/${id}` : '/players')} onSubmit={handleSubmit(submit)} isSubmitting={isSubmitting} error={error}><fieldset><legend>פרטים בסיסיים</legend><Field label="שם מלא" error={errors.full_name?.message}><input {...register('full_name')} autoFocus/></Field><div className="form-grid"><Field label="מספר חולצה" error={errors.shirt_number?.message}><input type="number" min="1" max="99" {...register('shirt_number')}/></Field><Field label="תאריך לידה"><input type="date" {...register('birth_date')}/></Field></div></fieldset><fieldset><legend>פרטים מקצועיים</legend><div className="form-grid"><Field label="תפקיד ראשי" error={errors.primary_position?.message}><select {...register('primary_position')}><option value="">בחירת תפקיד</option><option>שוער</option><option>בלם</option><option>מגן</option><option>קשר</option><option>כנף</option><option>חלוץ</option></select></Field><Field label="תפקיד משני"><input {...register('secondary_position')}/></Field><Field label="רגל דומיננטית"><select {...register('dominant_foot')}><option value="">לא הוזן</option><option value="right">ימין</option><option value="left">שמאל</option><option value="both">שתיהן</option></select></Field><Field label="סטטוס בסגל"><select {...register('squad_status')}><option value="active">פעיל</option><option value="injured">פציעה</option><option value="overload">עומס יתר</option><option value="suspended">מושעה</option><option value="inactive">לא פעיל</option></select></Field>{unavailable && <Field label="צפי היעדרות עד" error={errors.expected_absence_until?.message}><input type="date" {...register('expected_absence_until')}/></Field>}</div></fieldset><fieldset><legend>מידע נוסף</legend><Field label="מועדון קודם"><input {...register('previous_club')}/></Field><Field label="הערה מקצועית"><textarea rows={3} {...register('professional_notes')}/></Field></fieldset></FormLayout>;
}

export function MatchFormPage() {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id); const [match, setMatch] = useState<Match | null | undefined>(editing ? undefined : null); const [error, setError] = useState('');
  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<MatchValues>({ resolver: zodResolver(matchSchema), defaultValues: { home_or_away: 'home', competition_name: 'משחק אימון' } });
  useEffect(() => { if (!id) return; void matchesService.list().then((items) => { const current = items.find((item) => item.id === id) ?? null; setMatch(current); if (current) reset({ opponent_name: current.opponent_name, competition_name: current.competition_name, match_date: current.match_date ?? '', kickoff_time: current.kickoff_time ?? '', home_or_away: current.home_or_away, venue: current.venue ?? '' }); }).catch(() => setMatch(null)); }, [id, reset]);
  const submit = async (values: MatchValues) => { setError(''); try { if (match && id) await matchesService.update(id, values); else await matchesService.create(values); navigate(editing ? `/matches/${id}` : '/matches'); } catch { setError('לא ניתן לשמור את המשחק. השינויים לא נשמרו.'); } };
  if (editing && match === undefined) return <LoadingSkeleton lines={5} />;
  if (editing && !match) return <section className="empty-state"><h2>המשחק לא נמצא</h2></section>;
  return <FormLayout title={editing ? 'עריכת משחק' : 'הוספת משחק'} description="פרטי משחק, מועד ומיקום" onCancel={() => navigate(editing ? `/matches/${id}` : '/matches')} onSubmit={handleSubmit(submit)} isSubmitting={isSubmitting} error={error}><fieldset><legend>פרטי המשחק</legend><div className="form-grid"><Field label="שם היריבה" error={errors.opponent_name?.message}><input {...register('opponent_name')} autoFocus/></Field><Field label="מסגרת" error={errors.competition_name?.message}><input {...register('competition_name')}/></Field><Field label="בית או חוץ"><select {...register('home_or_away')}><option value="home">בית</option><option value="away">חוץ</option></select></Field><Field label="מגרש"><input {...register('venue')}/></Field><Field label="תאריך"><input type="date" {...register('match_date')}/></Field><Field label="שעת פתיחה"><input type="time" {...register('kickoff_time')}/></Field></div></fieldset></FormLayout>;
}

function FormLayout({ title, description, children, onSubmit, onCancel, isSubmitting, error }: { title: string; description: string; children: ReactNode; onSubmit: FormEventHandler<HTMLFormElement>; onCancel: () => void; isSubmitting: boolean; error: string }) { return <><PageHeader title={title} description={description}/><form className="page-form" onSubmit={onSubmit}>{children}{error && <p className="form-error">{error}</p>}<div className="form-actions"><SecondaryButton type="button" onClick={onCancel}>ביטול</SecondaryButton><PrimaryButton type="submit" disabled={isSubmitting}>{isSubmitting ? 'שומר…' : 'שמור שינויים'}</PrimaryButton></div></form></>; }
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="form-field">{label}<span>{children}</span>{error && <small className="field-error">{error}</small>}</label>; }
