import { useState } from 'react';
import { z } from 'zod';
import { authService } from '../services/authService';
import { isConfigured } from '../lib/supabase';
const passwordSchema = z.string().min(8, 'הסיסמה חייבת להכיל לפחות 8 תווים.');
export function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [mode, setMode] = useState<'login' | 'signup'>('login'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const isSignup = mode === 'signup';
  const switchMode = (next: 'login' | 'signup') => { setMode(next); setMessage(''); setPassword(''); setConfirmation(''); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); if (!z.string().email().safeParse(email).success) { setMessage('יש להזין כתובת דוא״ל תקינה.'); return; } if (!passwordSchema.safeParse(password).success) { setMessage('הסיסמה חייבת להכיל לפחות 8 תווים.'); return; } if (isSignup && password !== confirmation) { setMessage('אימות הסיסמה אינו תואם.'); return; } setBusy(true); try { if (isSignup) { await authService.signUp(email, password); setMode('login'); setPassword(''); setConfirmation(''); setMessage('ההרשמה הושלמה. אפשר להיכנס עם המייל והסיסמה שבחרת.'); } else { await authService.signIn(email, password); } } catch { setMessage(isSignup ? 'לא ניתן להשלים את ההרשמה. ייתכן שהמייל כבר קיים.' : 'כתובת המייל או הסיסמה שגויות.'); } finally { setBusy(false); } };
  return <div className="login squadrix-login"><img className="login-watermark" src="/squadrix-logo.png" alt="" aria-hidden="true"/><section><img className="login-logo" src="/squadrix-logo.png" alt="SQUADRIX"/><h1>SQUADRIX</h1><p>Football Team Operations</p><div className="auth-tabs" role="tablist" aria-label="כניסה למערכת"><button type="button" role="tab" aria-selected={!isSignup} className={!isSignup ? 'active' : ''} onClick={() => switchMode('login')}>כניסה</button><button type="button" role="tab" aria-selected={isSignup} className={isSignup ? 'active' : ''} onClick={() => switchMode('signup')}>הרשמה</button></div><form onSubmit={submit}><label>כתובת דוא״ל<input dir="ltr" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="name@example.com" autoComplete="email" /></label><label>סיסמה<input dir="ltr" type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={isSignup ? 'new-password' : 'current-password'} /></label>{isSignup && <label>אימות סיסמה<input dir="ltr" type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="new-password" /></label>}<button className="button primary" disabled={busy || !isConfigured}>{busy ? 'מעבד…' : isSignup ? 'יצירת חשבון' : 'כניסה למערכת'}</button></form>{isSignup && <p className="auth-note">נרשמים חדשים מקבלים הרשאת צפייה בלבד. שינוי הרשאה מתבצע על ידי מנהל המערכת.</p>}{!isConfigured && <p className="notice">נדרשת הגדרת Supabase בקובץ `.env` לפני התחברות.</p>}{message && <p className="notice">{message}</p>}</section></div>;
}
