import { useEffect, useMemo, useState } from 'react';
import { Save, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { LoadingSkeleton, PageHeader, PrimaryButton } from '../components/ui';
import { useBrand } from '../contexts/BrandContext';
import { useCurrentAuth } from '../contexts/AuthContext';
import { lineupsService } from '../services/lineupsService';
import { matchesService } from '../services/matchesService';
import { playersService } from '../services/playersService';
import type { Match, Player } from '../types/domain';

type Slot = { id: string; label: string; x: number; y: number };
type EligiblePlayer = { seasonId: string; name: string; number: number | null; position: string };

const formations: Record<string, Slot[]> = {
  '4-3-3': [{ id: 'gk', label: 'שוער', x: 50, y: 91 }, { id: 'rb', label: 'מגן ימני', x: 18, y: 73 }, { id: 'rcb', label: 'בלם ימני', x: 39, y: 76 }, { id: 'lcb', label: 'בלם שמאלי', x: 61, y: 76 }, { id: 'lb', label: 'מגן שמאלי', x: 82, y: 73 }, { id: 'rcm', label: 'קשר ימני', x: 27, y: 51 }, { id: 'cm', label: 'קשר מרכזי', x: 50, y: 45 }, { id: 'lcm', label: 'קשר שמאלי', x: 73, y: 51 }, { id: 'rw', label: 'כנף ימין', x: 20, y: 23 }, { id: 'st', label: 'חלוץ', x: 50, y: 17 }, { id: 'lw', label: 'כנף שמאל', x: 80, y: 23 }],
  '4-4-2': [{ id: 'gk', label: 'שוער', x: 50, y: 91 }, { id: 'rb', label: 'מגן ימני', x: 18, y: 73 }, { id: 'rcb', label: 'בלם ימני', x: 39, y: 76 }, { id: 'lcb', label: 'בלם שמאלי', x: 61, y: 76 }, { id: 'lb', label: 'מגן שמאלי', x: 82, y: 73 }, { id: 'rm', label: 'קשר ימין', x: 17, y: 48 }, { id: 'rcm', label: 'קשר מרכזי', x: 39, y: 45 }, { id: 'lcm', label: 'קשר מרכזי', x: 61, y: 45 }, { id: 'lm', label: 'קשר שמאל', x: 83, y: 48 }, { id: 'rst', label: 'חלוץ', x: 37, y: 18 }, { id: 'lst', label: 'חלוץ', x: 63, y: 18 }],
  '3-5-2': [{ id: 'gk', label: 'שוער', x: 50, y: 91 }, { id: 'rcb', label: 'בלם ימני', x: 25, y: 74 }, { id: 'cb', label: 'בלם', x: 50, y: 76 }, { id: 'lcb', label: 'בלם שמאלי', x: 75, y: 74 }, { id: 'rwb', label: 'כנף ימין', x: 12, y: 53 }, { id: 'rcm', label: 'קשר ימני', x: 35, y: 49 }, { id: 'cm', label: 'קשר מרכזי', x: 50, y: 43 }, { id: 'lcm', label: 'קשר שמאלי', x: 65, y: 49 }, { id: 'lwb', label: 'כנף שמאל', x: 88, y: 53 }, { id: 'rst', label: 'חלוץ', x: 37, y: 18 }, { id: 'lst', label: 'חלוץ', x: 63, y: 18 }],
};

const formationOptions: Record<string, Slot[]> = {
  ...formations,
  '4-2-3-1': [{ id: 'gk', label: 'שוער', x: 50, y: 91 }, { id: 'rb', label: 'מגן ימני', x: 18, y: 73 }, { id: 'rcb', label: 'בלם ימני', x: 39, y: 76 }, { id: 'lcb', label: 'בלם שמאלי', x: 61, y: 76 }, { id: 'lb', label: 'מגן שמאלי', x: 82, y: 73 }, { id: 'rdm', label: 'קשר אחורי ימין', x: 38, y: 56 }, { id: 'ldm', label: 'קשר אחורי שמאל', x: 62, y: 56 }, { id: 'ram', label: 'קשר התקפי ימין', x: 23, y: 35 }, { id: 'cam', label: 'קשר התקפי', x: 50, y: 30 }, { id: 'lam', label: 'קשר התקפי שמאל', x: 77, y: 35 }, { id: 'st', label: 'חלוץ', x: 50, y: 14 }],
  '4-1-4-1': [{ id: 'gk', label: 'שוער', x: 50, y: 91 }, { id: 'rb', label: 'מגן ימני', x: 18, y: 73 }, { id: 'rcb', label: 'בלם ימני', x: 39, y: 76 }, { id: 'lcb', label: 'בלם שמאלי', x: 61, y: 76 }, { id: 'lb', label: 'מגן שמאלי', x: 82, y: 73 }, { id: 'dm', label: 'קשר אחורי', x: 50, y: 59 }, { id: 'rm', label: 'קשר ימין', x: 17, y: 42 }, { id: 'rcm', label: 'קשר מרכזי', x: 39, y: 39 }, { id: 'lcm', label: 'קשר מרכזי', x: 61, y: 39 }, { id: 'lm', label: 'קשר שמאל', x: 83, y: 42 }, { id: 'st', label: 'חלוץ', x: 50, y: 14 }],
  '4-3-1-2': [{ id: 'gk', label: 'שוער', x: 50, y: 91 }, { id: 'rb', label: 'מגן ימני', x: 18, y: 73 }, { id: 'rcb', label: 'בלם ימני', x: 39, y: 76 }, { id: 'lcb', label: 'בלם שמאלי', x: 61, y: 76 }, { id: 'lb', label: 'מגן שמאלי', x: 82, y: 73 }, { id: 'rcm', label: 'קשר ימני', x: 28, y: 52 }, { id: 'cm', label: 'קשר מרכזי', x: 50, y: 48 }, { id: 'lcm', label: 'קשר שמאלי', x: 72, y: 52 }, { id: 'cam', label: 'קשר התקפי', x: 50, y: 31 }, { id: 'rst', label: 'חלוץ', x: 37, y: 14 }, { id: 'lst', label: 'חלוץ', x: 63, y: 14 }],
  '3-4-3': [{ id: 'gk', label: 'שוער', x: 50, y: 91 }, { id: 'rcb', label: 'בלם ימני', x: 25, y: 74 }, { id: 'cb', label: 'בלם', x: 50, y: 76 }, { id: 'lcb', label: 'בלם שמאלי', x: 75, y: 74 }, { id: 'rm', label: 'קשר ימין', x: 16, y: 52 }, { id: 'rcm', label: 'קשר מרכזי', x: 39, y: 48 }, { id: 'lcm', label: 'קשר מרכזי', x: 61, y: 48 }, { id: 'lm', label: 'קשר שמאל', x: 84, y: 52 }, { id: 'rw', label: 'כנף ימין', x: 20, y: 21 }, { id: 'st', label: 'חלוץ', x: 50, y: 14 }, { id: 'lw', label: 'כנף שמאל', x: 80, y: 21 }],
  '5-3-2': [{ id: 'gk', label: 'שוער', x: 50, y: 91 }, { id: 'rwb', label: 'מגן כנף ימין', x: 12, y: 67 }, { id: 'rcb', label: 'בלם ימני', x: 31, y: 76 }, { id: 'cb', label: 'בלם', x: 50, y: 78 }, { id: 'lcb', label: 'בלם שמאלי', x: 69, y: 76 }, { id: 'lwb', label: 'מגן כנף שמאל', x: 88, y: 67 }, { id: 'rcm', label: 'קשר ימני', x: 28, y: 49 }, { id: 'cm', label: 'קשר מרכזי', x: 50, y: 44 }, { id: 'lcm', label: 'קשר שמאלי', x: 72, y: 49 }, { id: 'rst', label: 'חלוץ', x: 37, y: 17 }, { id: 'lst', label: 'חלוץ', x: 63, y: 17 }],
};

Object.assign(formations, formationOptions);

function eligiblePlayers(players: Player[]): EligiblePlayer[] {
  return players.flatMap((player) => player.player_seasons.filter((season) => season.is_active && season.squad_status === 'active').map((season) => ({ seasonId: season.id, name: player.full_name, number: season.shirt_number, position: season.primary_position })));
}

export function NextMatchPage() {
  const { brand } = useBrand(); const { profile } = useCurrentAuth();
  const [matches, setMatches] = useState<Match[] | null>(null); const [available, setAvailable] = useState<EligiblePlayer[]>([]); const [matchId, setMatchId] = useState(''); const [formation, setFormation] = useState('4-3-3'); const [selection, setSelection] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const editable = profile?.role === 'admin' || profile?.role === 'professional_staff'; const slots = formationOptions[formation]; const selectedMatch = matches?.find((match) => match.id === matchId); const assigned = useMemo(() => new Set(slots.map((slot) => selection[slot.id]).filter(Boolean)), [selection, slots]);
  useEffect(() => { void Promise.all([matchesService.listUpcoming(), playersService.list()]).then(([upcoming, players]) => { setMatches(upcoming); setAvailable(eligiblePlayers(players)); setMatchId(upcoming[0]?.id ?? ''); }).catch(() => { setMatches([]); setAvailable([]); }); }, []);
  useEffect(() => { if (!matchId) { setSelection({}); return; } setMessage(''); void lineupsService.list(matchId).then((rows) => { setFormation(formationOptions[rows[0]?.formation] ? rows[0].formation : '4-3-3'); setSelection(Object.fromEntries(rows.filter((row) => available.some((player) => player.seasonId === row.player_season_id)).map((row) => [row.formation_slot, row.player_season_id]))); }).catch(() => setSelection({})); }, [matchId, available]);
  const changePlayer = (slotId: string, playerId: string) => setSelection((current) => { const next = { ...current, [slotId]: playerId }; if (playerId) Object.keys(next).forEach((key) => { if (key !== slotId && next[key] === playerId) next[key] = ''; }); return next; });
  const save = async () => { if (!matchId || assigned.size !== 11) { setMessage('יש לבחור 11 שחקנים זמינים לפני השמירה.'); return; } setSaving(true); setMessage(''); try { await lineupsService.save(matchId, slots.map((slot) => ({ formation, formation_slot: slot.id, player_season_id: selection[slot.id] })).filter((row) => row.player_season_id)); setMessage('ההרכב נשמר למשחק הבא.'); } catch { setMessage('לא ניתן לשמור את ההרכב. ודאו שה־migration של ההרכבים הורץ ב־Supabase.'); } finally { setSaving(false); } };
  if (matches === null) return <LoadingSkeleton lines={8}/>;
  if (!matches.length) return <><PageHeader title="המשחק הבא" description="הרכב מתוכנן לקראת המשחק הקרוב"/><section className="empty-state"><h2>אין משחקים מתוכננים</h2><p>הוסיפו משחק במצב „נקבע” כדי לבנות עבורו הרכב.</p><Link to="/matches/new">הוספת משחק</Link></section></>;
  return <><PageHeader title="המשחק הבא" description="בונים הרכב מתוך שחקנים פעילים בלבד — פצועים, מושעים ושחקנים בעומס יתר אינם זמינים לבחירה." action={editable ? <PrimaryButton onClick={() => void save()} disabled={saving || assigned.size !== 11}><Save size={17}/>{saving ? 'שומר…' : `שמירת הרכב (${assigned.size}/11)`}</PrimaryButton> : undefined}/><section className="next-match-meta data-card"><div><label>בחירת משחק<select value={matchId} onChange={(event) => setMatchId(event.target.value)}>{matches.map((match) => <option key={match.id} value={match.id}>{`${brand.name} מול ${match.opponent_name} · ${match.match_date ?? 'מועד טרם נקבע'}`}</option>)}</select></label><label>מערך<select value={formation} disabled={!editable} onChange={(event) => setFormation(event.target.value)}>{Object.keys(formations).map((value) => <option key={value} value={value}>{value}</option>)}</select></label></div>{selectedMatch && <p><b>{selectedMatch.opponent_name}</b> · {selectedMatch.home_or_away === 'home' ? 'בית' : 'חוץ'} · {selectedMatch.match_date ?? 'מועד טרם נקבע'} {selectedMatch.kickoff_time ? `· ${selectedMatch.kickoff_time}` : ''}</p>}</section><div className="lineup-layout"><section className="pitch" aria-label="הדמיית ההרכב על המגרש">{slots.map((slot) => { const player = available.find((item) => item.seasonId === selection[slot.id]); return <div key={slot.id} className="pitch-player" style={{ left: `${slot.x}%`, top: `${slot.y}%` }}><span className="jersey" style={{ backgroundColor: brand.primary_color, color: brand.secondary_color }}>{player?.number ?? '—'}</span><b>{player?.name ?? slot.label}</b><small>{player ? player.position : slot.label}</small></div>; })}</section><section className="lineup-picker data-card"><div className="lineup-picker-heading"><div><h2>הרכב פותח</h2><p><ShieldCheck size={16}/> {available.length} שחקנים זמינים לבחירה</p></div><span>{assigned.size}/11</span></div><div className="lineup-slots">{slots.map((slot) => <label key={slot.id}><span>{slot.label}</span><select value={selection[slot.id] ?? ''} disabled={!editable} onChange={(event) => changePlayer(slot.id, event.target.value)}><option value="">בחירת שחקן</option>{available.map((player) => <option key={player.seasonId} value={player.seasonId} disabled={assigned.has(player.seasonId) && selection[slot.id] !== player.seasonId}>{`${player.number ? `${player.number}. ` : ''}${player.name} · ${player.position}`}</option>)}</select></label>)}</div>{message && <p className={message.includes('נשמר') ? 'success-message' : 'form-error'}>{message}</p>}</section></div></>;
}
