import { useEffect, useMemo, useState } from 'react';
import { FileUp, MoreHorizontal, Plus } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PermissionGuard } from '../components/PermissionGuard';
import { EmptyState, LoadingSkeleton, PageHeader, PlayerAvatar, PrimaryButton, SearchInput, StatusBadge } from '../components/ui';
import { playersService } from '../services/playersService';
import type { Player } from '../types/domain';

export function PlayersPage() {
  const [players, setPlayers] = useState<Player[] | null>(null); const [query, setQuery] = useState('');
  useEffect(() => { void playersService.list().then(setPlayers).catch(() => setPlayers([])); }, []);
  const filtered = useMemo(() => players?.filter((player) => player.full_name.includes(query)) ?? [], [players, query]);
  const addAction = <PermissionGuard roles={['admin', 'professional_staff']}><span className="inline-actions"><Link to="/players/import"><button className="button secondary"><FileUp size={18}/>ייבוא CSV</button></Link><Link to="/players/new"><PrimaryButton><Plus size={18}/>הוסף שחקן</PrimaryButton></Link></span></PermissionGuard>;
  return <><PageHeader title="סגל הקבוצה" description={players ? `${players.length} שחקנים בעונה הנוכחית` : 'טוען סגל'} action={addAction}/><div className="filter-bar"><SearchInput value={query} onChange={setQuery}/>{query && <button className="clear-filter" onClick={() => setQuery('')}>נקה מסננים</button>}<span>{filtered.length} תוצאות</span></div>{players === null ? <LoadingSkeleton lines={8}/> : !filtered.length ? <EmptyState title={query ? 'לא נמצאו שחקנים' : 'אין שחקנים בסגל'} text={query ? 'נסו חיפוש אחר.' : 'התחילו בהוספת השחקן הראשון לעונה הנוכחית.'} action={!query ? addAction : undefined}/> : <><div className="data-card table-wrap desktop-table"><table><thead><tr><th>שחקן</th><th>מספר</th><th>תפקיד</th><th>סטטוס</th><th>הופעות</th><th>דקות</th><th>שערים</th><th>בישולים</th><th><span className="sr-only">פעולות</span></th></tr></thead><tbody>{filtered.map((player) => { const season = player.player_seasons[0]; const stats = season?.player_season_statistics; return <tr key={player.id}><td><Link to={`/players/${player.id}`} className="player-cell player-link"><PlayerAvatar name={player.full_name} src={player.photo_url}/><b>{player.full_name}</b></Link></td><td>{season?.shirt_number ?? '—'}</td><td>{season?.primary_position ?? '—'}</td><td>{season && <StatusBadge status={season.squad_status}/>}</td><td>{stats?.appearances ?? '—'}</td><td>{stats?.minutes_played ?? '—'}</td><td>{stats?.goals ?? '—'}</td><td>{stats?.assists ?? '—'}</td><td><PermissionGuard roles={['admin', 'professional_staff']}><button className="icon-button" aria-label={`פעולות עבור ${player.full_name}`} title="פעולות"><MoreHorizontal size={20}/></button></PermissionGuard></td></tr>; })}</tbody></table></div><div className="mobile-player-list">{filtered.map((player) => { const season = player.player_seasons[0]; const stats = season?.player_season_statistics; return <Link to={`/players/${player.id}`} className="player-mobile-card" key={player.id}><PlayerAvatar name={player.full_name} src={player.photo_url}/><div><b>{player.full_name}</b><span>{season?.shirt_number ? `#${season.shirt_number} · ` : ''}{season?.primary_position ?? 'ללא תפקיד'}</span></div>{season && <StatusBadge status={season.squad_status}/>}<dl><div><dt>דקות</dt><dd>{stats?.minutes_played ?? '—'}</dd></div><div><dt>שערים</dt><dd>{stats?.goals ?? '—'}</dd></div><div><dt>בישולים</dt><dd>{stats?.assists ?? '—'}</dd></div></dl></Link>; })}</div></>}</>;
}
