import { useEffect, useState } from 'react';
import { ArrowRight, Edit3, Trash2 } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { KpiCard, LoadingSkeleton, PageHeader, PlayerAvatar, PrimaryButton, SecondaryButton, StatusBadge } from '../components/ui';
import { PermissionGuard } from '../components/PermissionGuard';
import { playersService } from '../services/playersService';
import { statisticsService, type PlayerPerformance } from '../services/statisticsService';
import type { Player } from '../types/domain';

export function PlayerDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [player, setPlayer] = useState<Player | null | undefined>(undefined); const [performance, setPerformance] = useState<PlayerPerformance | null>(null); const [confirm, setConfirm] = useState(false); const [deleting, setDeleting] = useState(false);
  useEffect(() => { void Promise.all([playersService.list(), statisticsService.playerPerformance()]).then(([items, performances]) => { const current = items.find((item) => item.id === id) ?? null; setPlayer(current); setPerformance(current?.player_seasons[0] ? performances.find((item) => item.playerSeasonId === current.player_seasons[0].id) ?? null : null); }).catch(() => setPlayer(null)); }, [id]);
  if (player === undefined) return <LoadingSkeleton lines={5}/>;
  if (!player) return <section className="empty-state"><h2>השחקן לא נמצא</h2><Link to="/players">חזרה לסגל</Link></section>;
  const season = player.player_seasons[0]; const stats = performance;
  const remove = async () => { if (!id) return; setDeleting(true); try { await playersService.remove(id); navigate('/players'); } finally { setDeleting(false); } };
  return <><Link className="back-link" to="/players"><ArrowRight size={16}/>חזרה לסגל</Link><PageHeader title={player.full_name} description={season ? `${season.primary_position} · ${season.shirt_number ? `#${season.shirt_number}` : 'ללא מספר חולצה'}` : 'טרם שובץ לעונה'} action={<PermissionGuard roles={['admin', 'professional_staff']}><span className="inline-actions"><PrimaryButton onClick={() => navigate(`/players/${id}/edit`)}><Edit3 size={17}/>ערוך שחקן</PrimaryButton><SecondaryButton onClick={() => setConfirm(true)}><Trash2 size={17}/>מחיקה</SecondaryButton></span></PermissionGuard>}/><section className="player-summary"><PlayerAvatar name={player.full_name} src={player.photo_url}/><div><strong>{player.full_name}</strong>{season && <StatusBadge status={season.squad_status}/>}</div></section><div className="kpis player-kpis"><KpiCard label="הופעות" value={stats?.appearances ?? '—'}/><KpiCard label="הרכבים" value={stats?.starts ?? '—'}/><KpiCard label="דקות" value={stats?.minutes ?? '—'}/><KpiCard label="שערים" value={stats?.goals ?? '—'}/><KpiCard label="בישולים" value={stats?.assists ?? '—'}/></div><div className="statistics-detail"><section className="data-card"><h2>שימוש במשחקים</h2><dl className="details-list"><div><dt>פתח בהרכב</dt><dd>{stats?.starts ?? '—'}</dd></div><div><dt>נכנס כמחליף</dt><dd>{stats?.substituteAppearances ?? '—'}</dd></div><div><dt>הוחלף</dt><dd>{stats?.substituted ?? '—'}</dd></div><div><dt>הופעות</dt><dd>{stats?.appearances ?? '—'}</dd></div></dl></section><section className="data-card"><h2>תרומה ומשמעת</h2><dl className="details-list"><div><dt>שערים</dt><dd>{stats?.goals ?? '—'}</dd></div><div><dt>בישולים</dt><dd>{stats?.assists ?? '—'}</dd></div><div><dt>כרטיסים צהובים</dt><dd>{stats?.yellowCards ?? '—'}</dd></div><div><dt>כרטיסים אדומים</dt><dd>{stats?.redCards ?? '—'}</dd></div></dl></section><section className="data-card"><h2>סקירה מקצועית</h2><dl className="details-list"><div><dt>תפקיד ראשי</dt><dd>{season?.primary_position ?? 'טרם הוזן'}</dd></div><div><dt>תפקיד משני</dt><dd>{season?.secondary_position ?? '—'}</dd></div><div><dt>מספר חולצה</dt><dd>{season?.shirt_number ?? '—'}</dd></div><div><dt>צפי היעדרות</dt><dd>{season?.expected_absence_until ?? 'אין'}</dd></div></dl></section></div>{confirm && <ConfirmDialog title={`למחוק את ${player.full_name}?`} description="פעולה זו תמחק את השחקן ואת שיוכיו לעונות. אין אפשרות לבטל אותה." onCancel={() => setConfirm(false)} onConfirm={() => void remove()} busy={deleting}/>}</>;
}
