import type { ButtonHTMLAttributes, ReactNode } from 'react'; import { AlertCircle, CheckCircle2, CircleHelp, Search, UserRound } from 'lucide-react';
import type { MatchStatus, PlayerStatus } from '../types/domain';
export function PrimaryButton(props: ButtonHTMLAttributes<HTMLButtonElement>) { return <button {...props} className={`button primary ${props.className ?? ''}`} />; }
export function SecondaryButton(props: ButtonHTMLAttributes<HTMLButtonElement>) { return <button {...props} className={`button secondary ${props.className ?? ''}`} />; }
export function PageHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="page-header"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>; }
const labels: Record<PlayerStatus | MatchStatus, string> = { active: 'פעיל', injured: 'פצוע', overload: 'עומס יתר', suspended: 'מושעה', inactive: 'לא פעיל', draft: 'טיוטה', scheduled: 'נקבע', postponed: 'נדחה', cancelled: 'בוטל', completed: 'הושלם', missing_data: 'ממתין להשלמה' };
export function StatusBadge({ status }: { status: PlayerStatus | MatchStatus }) { return <span className={`badge badge-${status}`}>{labels[status]}</span>; }
export function KpiCard({ label, value, note, icon }: { label: string; value: string | number; note?: string; icon?: ReactNode }) { return <article className="kpi-card"><div className="kpi-label">{icon}<span>{label}</span></div><strong>{value}</strong>{note && <small>{note}</small>}</article>; }
export function EmptyState({ title, text, action }: { title: string; text: string; action?: ReactNode }) { return <section className="empty-state"><CircleHelp size={28} aria-hidden="true"/><h2>{title}</h2><p>{text}</p>{action}</section>; }
export function ErrorState({ retry }: { retry?: () => void }) { return <section className="error-state"><AlertCircle aria-hidden="true"/><div><strong>לא ניתן לטעון את הנתונים</strong><p>החיבור לשרת נכשל. המידע לא השתנה.</p></div>{retry && <SecondaryButton onClick={retry}>נסה שוב</SecondaryButton>}</section>; }
export function LoadingSkeleton({ lines = 3 }: { lines?: number }) { return <div className="skeleton" aria-label="טוען תוכן">{Array.from({ length: lines }, (_, index) => <i key={index} />)}</div>; }
export function SearchInput({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label className="search"><Search size={18}/><span className="sr-only">חיפוש לפי שם שחקן</span><input value={value} onChange={(e) => onChange(e.target.value)} placeholder="חיפוש לפי שם שחקן" /></label>; }
export function PlayerAvatar({ name, src }: { name: string; src?: string | null }) { return src ? <img className="avatar" src={src} alt={`תמונת ${name}`} /> : <span className="avatar fallback" aria-label={`ללא תמונה: ${name}`}><UserRound size={18}/></span>; }
export function Completion({ completed }: { completed: boolean }) { return <span className={completed ? 'completion good' : 'completion warning'}>{completed ? <CheckCircle2 size={16}/> : <AlertCircle size={16}/>} {completed ? 'הנתונים הושלמו' : 'ממתין להשלמה'}</span>; }
